version: '3'
services:
  acron:
    image: funnyzak/cron:latest
    privileged: false
    container_name: crons
    tty: true
    environment:
      - TZ=Asia/Shanghai
      - LANG=C.UTF-8
      - CRON_TAIL=1
      - CRON_STRINGS=* * * * * /scripts/echo.sh >> /var/log/cron.log 2>&1
    restart: on-failure
    volumes:
      - ./cron/scripts:/scripts
      - ./cron/crontab:/etc/cron.d # crontab files
      - ./cron/log:/var/log/cron # cron log