name: Get Latest GHCR Image Version

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image name, e.g. my-image'
        required: true
        type: string

  workflow_call:
    inputs:
      image_name:
        description: 'Image name, e.g. my-image'
        required: true
        type: string

permissions:
  packages: write

jobs:
  get-latest-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest version
        run: |
          REPO="${{ github.repository }}"
          IMAGE="${{ github.event.inputs.image_name }}"
          TAGS=$(gh api -H "Accept: application/vnd.github+json" /repos/$REPO/packages/container/$IMAGE/versions --paginate | jq -r '.[].metadata.container.tags[]') || { echo "Failed to fetch tags."; exit 1; }
          
          LATEST_VERSION=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -rV | head -n 1)

          if [ -z "$LATEST_VERSION" ]; then
            echo "No stable version found."
            exit 1
          fi

          echo "Latest version is $LATEST_VERSION"
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload variable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.image_name }}-ghcr-lastest-version
          path: ${{ env.LATEST_VERSION }}