name: Deploy GitHub Pages

on:
  push:
    # paths:
    #   - 'README.md'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set jeckyll config
      run: |
        echo "theme: jekyll-theme-cayman" > _config.yml
        echo "show_downloads: true" >> _config.yml
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      # if: ${{ github.ref == 'refs/heads/main' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
        cname: docker-release.gh.yycc.dev
        publish_branch: gh-pages
        enable_jekyll: true
        keep_files: false
        force_orphan: true
        commit_message: ${{ github.event.head_commit.message }}