name: Docker Image Publish
on:
  workflow_call:
    inputs:
      docker_tag:
        description: 'Docker image tag, e.g. latest'
        required: true
        type: string
        default: 'latest'
      docker_context:
        description: 'Docker build context, default is current directory, e.g. ./Docker/y-webrtc-signaling'
        required: true
        type: string
        default: './Docker/y-webrtc-signaling'
  workflow_dispatch:
    inputs:
      docker_tag:
        description: 'Docker image tag, e.g. latest'
        required: true
        type: string
        default: 'latest'
      docker_context:
        description: 'Docker build context, default is current directory, e.g. ./Docker/y-webrtc-signaling'
        required: true
        type: string
        default: './Docker/y-webrtc-signaling'

permissions:
  packages: write
  contents: read

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' || github.event_name == 'push'
    outputs:
      IMAGE_FULL_NAME: ${{ steps.set_vars.outputs.IMAGE_FULL_NAME }}
      IMAGE_NAME: ${{ steps.set_vars.outputs.IMAGE_NAME }}
      BUILD_TRIGGER_DESCRIPTION: ${{ steps.set_vars.outputs.BUILD_TRIGGER_DESCRIPTION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Determine Docker Context
        id: determine-context
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            DOCKER_CONTEXT="${{ github.event.inputs.docker_context }}"
          elif [ "${{ github.event_name }}" == "workflow_call" ]; then
            DOCKER_CONTEXT="${{ inputs.docker_context }}"
          else
            DOCKER_CONTEXT="./Docker/y-webrtc-signaling"
          fi
          echo "docker_context=$DOCKER_CONTEXT" >> $GITHUB_OUTPUT

      - name: Check context exist
        run: |
          if [ ! -d "${{ steps.determine-context.outputs.docker_context }}" ]; then
            echo "Docker context ${{ steps.determine-context.outputs.docker_context }} does not exist"
            exit 1
          fi

      - name: Set vars
        id: set_vars
        run: |
          CONTEXT="${{ steps.determine-context.outputs.docker_context }}"
          TAG="${{ github.event.inputs.docker_tag || inputs.docker_tag }}"
          {
            echo "IMAGE_FULL_NAME=${{ github.actor }}/$(basename $CONTEXT):$TAG"
            echo "IMAGE_NAME=${{ github.actor }}/$(basename $CONTEXT)"
            echo "BUILD_TRIGGER_DESCRIPTION=Build and push Docker image ${{ github.actor }}/$(basename $CONTEXT):$TAG"
          } >> $GITHUB_OUTPUT
        

  docker-release:
    name: Publish Docker images
    needs: [setup]
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Build trigger description
        run: |
          echo "The image full name is ${{ needs.setup.outputs.IMAGE_FULL_NAME }}"
          echo "The image name is ${{ needs.setup.outputs.IMAGE_NAME }}"
          echo "The build trigger description is ${{ needs.setup.outputs.BUILD_TRIGGER_DESCRIPTION }}"
          echo "The"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to ALIYUNCS
        uses: docker/login-action@v3
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ALIYUNCS_PASSWORD }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ github.event.inputs.docker_context }}
          push: true
          tags: |
            ${{ needs.setup.outputs.IMAGE_FULL_NAME }}
            registry.cn-beijing.aliyuncs.com/${{ needs.setup.outputs.IMAGE_FULL_NAME }}
            ghcr.io/${{ needs.setup.outputs.IMAGE_FULL_NAME }}
          platforms: |
            linux/amd64
            linux/arm64
            linux/arm/v7

      - name: Send Apprise Notification
        run: |
          curl -X POST \
            -F "tag=office,ycgo" \
            -F "body=${{ github.event_name }}: ${{ github.repository }} ${{ github.sha }} ${{ needs.setup.outputs.BUILD_TRIGGER_DESCRIPTION }} Link: https://hub.docker.com/r/${{ needs.setup.outputs.IMAGE_NAME }}" \
            "${{ secrets.APPRISE_HTTP_URL }}"
