name: Watch Nginx Release

on:
  # schedule:
  #   - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write
  packages: write


jobs:
  docker_latest_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Get version
        uses: luoqiz/docker-images-latest-version@master
        id: get_version
        with:
          image: funnyzak/nginx

  watch_new_release:
    runs-on: ubuntu-latest
    needs: docker_latest_version
    outputs:
      new_version: ${{ steps.get-latest-release.outputs.new_version }}
    steps:
      - name: Get latest release version
        id: get-latest-release
        run: |
          echo new_version=$(curl -s https://nginx.org/en/download.html | grep -oP 'nginx-\K[0-9.]+(?=</a>)' | head -n 1)
          echo "Current Official version: $new_version"
          echo "Current Docker version: ${{ needs.docker_latest_version.outputs.version }}"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "DOCKER_VERSION=${{ needs.docker_latest_version.outputs.version }}" >> $GITHUB_OUTPUT